repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  -   id: mypy
- repo: https://github.com/crate-ci/typos
  rev: v1.16.25
  hooks:
    - id: typos
