version: '3'

services:
  metabase:
    image: scurrilous/metabase # official image does not support arm64 :(. See https://github.com/metabase/metabase/issues/13119
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: metabase-db
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  metabase-db:
    image: postgres:latest
    container_name: metabase-db
    hostname: metabase-db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metanet1
  stocklake-db:
    image: postgres:16
    container_name: stocklake-db
    hostname: stocklake-db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stocklake
    networks:
      - metanet1


networks:
  metanet1:
    driver: bridge

volumes:
  postgres_data:
