version: '3'

services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stocklake

volumes:
  postgres_data:
