site_name: Stocklake
theme:
  - material
  - features:
    - content.code.copy

markdown_extensions:
    - mkdocs-click
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/2/twemoji.min.css

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [stocklake]
