"""optional columns are added for polygonapi financials data

Revision ID: 3ae0f3268b61
Revises: e3eb558b51d1
Create Date: 2024-06-25 20:43:07.899719

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3ae0f3268b61"
down_revision: Union[str, None] = "e3eb558b51d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
