"""optional columns are added for polygonapi financials data

Revision ID: 52592690dfd3
Revises: ec7e9fd3b783
Create Date: 2024-06-25 22:43:34.305848

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "52592690dfd3"
down_revision: Union[str, None] = "ec7e9fd3b783"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
