"""Add name column for nasdaqapi data table

Revision ID: 5e20e944d431
Revises: bf8106d0ce4c
Create Date: 2024-05-04 11:35:25.863891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e20e944d431'
down_revision: Union[str, None] = 'bf8106d0ce4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nasdaq_api_data', sa.Column('name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nasdaq_api_data', 'name')
    # ### end Alembic commands ###
