"""use bigint for the transaction timestamp

Revision ID: 7681f01ca0f8
Revises: ba2f1e21749f
Create Date: 2024-07-15 20:17:18.300989

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7681f01ca0f8"
down_revision: Union[str, None] = "ba2f1e21749f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "polygonapi_aggregates_bars_data",
        "timestamp_ms",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "polygonapi_aggregates_bars_data",
        "timestamp_ms",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
