"""change fiscal_year nullable integer

Revision ID: 84fb754ea7f6
Revises: 6b0b5d33d3e1
Create Date: 2024-07-02 23:15:21.923983

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "84fb754ea7f6"
down_revision: Union[str, None] = "6b0b5d33d3e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
