"""pct_change column should be nullable

Revision ID: e3eb558b51d1
Revises: 3ae9ebc67811
Create Date: 2024-06-23 11:22:07.024831

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e3eb558b51d1"
down_revision: Union[str, None] = "3ae9ebc67811"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
