"""optional columns are added for polygonapi financials data

Revision ID: ec7e9fd3b783
Revises: 3ae0f3268b61
Create Date: 2024-06-25 22:42:31.694935

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ec7e9fd3b783"
down_revision: Union[str, None] = "3ae0f3268b61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
