name: CI
on:
  push:
    paths:
      - '**.py'

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: stocklake

    steps:
      - uses: actions/checkout@v4
      # NOTE: Read python version from .python-version in the workging directory.
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: Create venv and install python packages
        run: |
          python -m pip install --upgrade pip && pip install -r dev-requirements.txt && pip install -r requirements.txt
      - name: Run Ruff Linter
        run: |
          ruff check .
      - name: Run mypy Type Checking
        run: |
          mypy .
      - name: Run pytest
        run: |
          pytest
