name: Release

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: "3.11"

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Hatch
        run: python3 -m pip install hatch
      - name: Install dependences
        run: hatch build
      - name: Publish package
        if: "startsWith(github.ref, 'refs/tags/')"
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          hatch publish
